services:
  bot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DB_PATH=/data/dipomacy.db
      - DEFAULT_MAP_PATH=/app/diplo_engine/maps/map_test.json
    volumes:
      - bot_data:/data
  
volumes:
  bot_data: